name: adopptrs
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - jupyter
  - numpy
  - pip
  - python=3.9
  - pytorch
  - cudatoolkit=11.3
  - scipy
  - pip:
    - matplotlib
    - opencv-python
    - owslib
    - pandas
    - pillow
    - torchsummary
    - torchvision
